/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conv;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

import org.junit.jupiter.api.BeforeEach;

class ConverterTest {
    private Converter converter;

    @BeforeEach
    public void doBefore() {
        converter = new Converter();
    }

    @Test
    void testAdd() {
        assertEquals(5, converter.add(2, 3));
        assertEquals(0, converter.add(0, 0));
        assertEquals(0, converter.add(-1, 1));
        assertEquals(0, converter.add(1, -1));
    }

    @Test
    void testAddPositive() {
        assertEquals(5, converter.addPositive(2, 3, 0));
        assertEquals(0, converter.addPositive(0, 0, 0));
        assertEquals(1, converter.addPositive(-1, 1, 0));
        assertEquals(1, converter.addPositive(1, -1, 0));
        assertEquals(6, converter.addPositive(1, 2, 3));

        assertEquals(3, converter.addPositive(-1, -2, 3));
        assertEquals(1, converter.addPositive(1, -2, -3));
        assertEquals(2, converter.addPositive(-1, 2, -3));
    }

    @Test
    void testAddList() {
        assertEquals(5, converter.addList(Arrays.asList( 2, 3 )));
        assertEquals(0, converter.addList(Arrays.asList( 0, 0 )));
        assertEquals(0, converter.addList(Arrays.asList( -1, 1 )));
        assertEquals(0, converter.addList(Arrays.asList( 1, -1 )));
        assertEquals(15, converter.addList(Arrays.asList( 1, 2, 3, 4, 5 )));
        assertEquals(0, converter.addList(Arrays.asList()));
        assertEquals(-5, converter.addList(Arrays.asList( -2, -3 )));
    }

    @Test
    void testAddPositiveList() {
        assertEquals(5, converter.addPositiveList(Arrays.asList( 2, 3 )));
        assertEquals(0, converter.addPositiveList(Arrays.asList( 0, 0 )));
        assertEquals(1, converter.addPositiveList(Arrays.asList( -1, 1 )));
        assertEquals(1, converter.addPositiveList(Arrays.asList( 1, -1 )));
        assertEquals(15, converter.addPositiveList(Arrays.asList( 1, 2, 3, 4, 5 )));
        assertEquals(0, converter.addPositiveList(Arrays.asList()));
        assertEquals(0, converter.addPositiveList(Arrays.asList( -2, -3 )));
    }
}